
services:
  db: # run postgres container on port 5432
    image: postgres:16
    container_name: quotes-keeper-postgres
    restart: unless-stopped
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotes-keeper
    ports: 
      - "5432:5432"
    volumes: # map volume to /var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
volumes: # create volume
  postgres_data:
